---
- name: Install tools on DevTools
  hosts: test
  become: yes

  tasks:

  - name: Install programs
    apt:
      update_cache: yes
      name: "{{packages}}"
    vars:
      packages:
      - openjdk-8-jdk
      - ansible
      - maven
      - git-core
      - wget
      - docker.io

  - name: Add Jenkins apt repository key.
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present

  - name: Add Jenkins apt repository.
    apt_repository:
      repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
      state: present
      update_cache: true

  - name: Install Jenkins
    apt:
      name: jenkins
      state: present
  - name: Allow port 8080
    shell: iptables -I INPUT -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
  - name: Start the server
    service:
      name: jenkins
      state: started

  - name: Get Admin Password
    become: yes
    become_method: sudo
    command: cat /var/lib/jenkins/secrets/initialAdminPassword

  - name: Install Artifactory
    shell: sudo fallocate -l 2G /swapfile
    shell: sudo chmod 600 /swapfile
    shell: sudo mkswap /swapfile
    shell: sudo swapon /swapfile
    shell: sudo echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
    shell: sudo docker pull docker.bintray.io/jfrog/artifactory-cpp-ce
    shell: sudo mkdir -p /jfrog/artifactory
    shell: sudo chown -R 1030 /jfrog/
    shell: sudo docker run --name artifactory -d -p 8081:8081 \
      -v /jfrog/artifactory:/var/opt/jfrog/artifactory \
      docker.bintray.io/jfrog/artifactory-oss:latest
...
